# fly.toml app configuration file generated for go-main-frosty-cloud-6258 on 2024-04-09T20:31:40+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'go-wahoo-cloud-api'
primary_region = 'lhr'

[build]

[env]
  PORT = "8080"
  REDIRECT_URI = "https://go-wahoo-cloud-api.fly.dev/"
  WAHOO_CLIENT_ID = "***REDACTED***"
  WAHOO_AUTH_BASE_URL = "https://api.wahooligan.com/oauth/authorize"
  WAHOO_TOKEN_BASE_URL = "https://api.wahooligan.com/oauth/token"
  TIGRIS_ENABLED = "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
