# fly.toml app configuration file generated for go-wahoo-cloud-api-weathered-log-1699 on 2025-10-15T22:35:38+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'go-wahoo-cloud-api'
primary_region = 'lhr'

[build]

[env]
  PORT = '8080'
  REDIRECT_URI = 'https://go-wahoo-cloud-api.fly.dev/'
  TIGRIS_ENABLED = 'true'
  WAHOO_AUTH_BASE_URL = 'https://api.wahooligan.com/oauth/authorize'
  WAHOO_TOKEN_BASE_URL = 'https://api.wahooligan.com/oauth/token'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
